# Generated by Django 4.1.5 on 2023-01-28 02:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=34, verbose_name='first name')),
                ('first_name_en', models.CharField(max_length=34, verbose_name='first name english')),
                ('last_name', models.CharField(max_length=34, verbose_name='last name')),
                ('last_name_en', models.CharField(max_length=34, verbose_name='last name english')),
                ('position', models.CharField(max_length=120, verbose_name='position')),
                ('position_en', models.CharField(max_length=120, verbose_name='position english')),
                ('phone_number', models.CharField(max_length=18, verbose_name='phone number')),
                ('email', models.EmailField(max_length=120, verbose_name='email')),
                ('address', models.CharField(max_length=250, verbose_name='address')),
                ('describe', ckeditor.fields.RichTextField(verbose_name='describe')),
                ('image_background', models.ImageField(default='medical_wall.jpg', help_text='recommended: Image(1920X1279)', upload_to='', verbose_name='image background')),
                ('image_logo', models.FileField(help_text='recommended: Image(format is .svg)', upload_to='', verbose_name='image logo')),
                ('image_about', models.ImageField(help_text='recommended: Image(1680X1120)', upload_to='', verbose_name='Image for about page')),
                ('image_avatar1', models.ImageField(help_text='recommended: Image(100X100)', upload_to='', verbose_name='Image for big avatar')),
                ('image_avatar2', models.ImageField(help_text='recommended: Image(80X80)', upload_to='', verbose_name='Image for medium avatar')),
                ('image_avatar3', models.ImageField(help_text='recommended: Image(60X60)', upload_to='', verbose_name='Image for small avatar')),
                ('describe_short', models.TextField(max_length=250, verbose_name='describe short')),
                ('introduction', models.CharField(max_length=200, verbose_name='introduction')),
                ('facebook', models.CharField(default='#', max_length=120, verbose_name='facebook')),
                ('twitter', models.CharField(default='#', max_length=120, verbose_name='twitter')),
                ('instagram', models.CharField(default='#', max_length=120, verbose_name='instagram')),
                ('instagram_id', models.CharField(max_length=64, verbose_name='instagram id')),
                ('pinterest', models.CharField(default='#', max_length=120, verbose_name='pinterest')),
                ('youtube', models.CharField(default='#', max_length=120, verbose_name='youtube')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Me',
                'verbose_name_plural': 'About Me',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=34, verbose_name='fullname')),
                ('email', models.EmailField(max_length=120, verbose_name='email')),
                ('subject', models.CharField(max_length=120, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instagram Post',
                'verbose_name_plural': 'Instagram Posts',
                'ordering': ('-created',),
            },
        ),
    ]
