# Generated by Django 4.1.5 on 2023-01-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='instagram id'),
        ),
    ]
