# Generated by Django 4.1.5 on 2023-01-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image_logo',
            field=models.FileField(help_text='recommended: Image(format is .svg)', upload_to='', verbose_name='image logo'),
        ),
    ]
