# Generated by Django 4.1.5 on 2023-01-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_aboutme_image_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='image_background',
            field=models.ImageField(default='medical_wall.jpg', upload_to='', verbose_name='image background'),
        ),
    ]
