# Generated by Django 4.1.5 on 2023-01-24 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttag',
            name='name_en',
            field=models.CharField(default='salam', max_length=34, verbose_name='name english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posttag',
            name='slug',
            field=models.SlugField(default='salam', max_length=68, verbose_name='slug english'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 15, 45, 9, 516372, tzinfo=datetime.timezone.utc), verbose_name='published at'),
        ),
    ]
