# Generated by Django 4.1.5 on 2023-01-24 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_published_at_alter_posttag_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttag',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='posttag',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 16, 27, 28, 776467, tzinfo=datetime.timezone.utc), verbose_name='published at'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='website',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='website'),
        ),
    ]
