# Generated by Django 4.1.5 on 2023-01-24 18:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_posttag_name_en_remove_posttag_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 18, 39, 53, 305819, tzinfo=datetime.timezone.utc), verbose_name='published at'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.postcomment', verbose_name='parent'),
        ),
    ]
