# Generated by Django 4.1.5 on 2023-01-24 19:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_published_at_alter_postcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 19, 1, 21, 325032, tzinfo=datetime.timezone.utc), verbose_name='published at'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='post'),
        ),
    ]
