# Generated by Django 4.1.5 on 2023-01-25 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_introduction_alter_post_published_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Introduction',
            new_name='introduction',
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 5, 21, 58, 952344, tzinfo=datetime.timezone.utc), verbose_name='published at'),
        ),
    ]
