# Generated by Django 4.1.5 on 2023-01-25 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_introduction_post_introduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 6, 1, 38, 353122, tzinfo=datetime.timezone.utc), verbose_name='published at'),
        ),
    ]
